### ISSUE TITLE
question: read/write same component from system

### ISSUE THREAD

**Issue by bjadamson** [SuperV1234/ecst#14]
Hey, hope things are going well. I have a simple question, is it possible to read/write the same component type from a system?

I'm getting the following compilation error:
> home/benjamin/github/BoomHS/external/ecst/include/ecst/signature/./system/./data.hpp:80:13: error: static_assert failed "decltype(!mp::list::any_common_element( s_read_ctag_list(), s_write_ctag_list())){}"
            ECST_S_ASSERT_DT(!mp::list::any_common_element( // .
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/benjamin/github/BoomHS/external/ecst/include/./ecst/./aliases/assert.hpp:27:31: note: expanded from macro 'ECST_S_ASSERT_DT'
#define ECST_S_ASSERT_DT(...) ECST_S_ASSERT(decltype(__VA_ARGS__){})
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/benjamin/github/BoomHS/external/ecst/include/./ecst/./aliases/assert.hpp:20:28: note: expanded from macro 'ECST_S_ASSERT'
#define ECST_S_ASSERT(...) VRM_CORE_STATIC_ASSERT_NM(__VA_ARGS__)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/benjamin/github/BoomHS/external/ecst/extlibs/vrm_core/include/vrm/core/assert/static_assert_macros.hpp:17:40: note: expanded from macro 'VRM_CORE_STATIC_ASSERT_NM'
#define VRM_CORE_STATIC_ASSERT_NM(...) static_assert(__VA_ARGS__, VRM_PP_TOSTR(__VA_ARGS__))
                                       ^             ~~~~~~~~~~~
/home/benjamin/github/BoomHS/external/ecst/include/ecst/signature/./system/./data.hpp:56:24: note: in instantiation of template class 'ecst::signature::system::impl::data<ecst::tag::system::impl::tag_impl<s::randompos_system>,
      ecst::mp::option_map::impl::data<boost::hana::map<boost::hana::detail::hash_table<boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 0>, 0>,
      boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 1>, 1>, boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 2>, 2>,
      boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 3>, 3>, boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 4>, 4> >,
      boost::hana::basic_tuple<boost::hana::pair<std::__1::integral_constant<unsigned long, 0>, boost::hana::pair<ecst::inner_parallelism::strategy::none::impl::parameters, boost::hana::integral_constant<bool, true> > >,
      boost::hana::pair<std::__1::integral_constant<unsigned long, 1>, boost::hana::pair<boost::hana::basic_tuple<>, boost::hana::integral_constant<bool, false> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 2>,
      boost::hana::pair<boost::hana::basic_tuple<ecst::tag::component::impl::tag_impl<game::world_coordinate> >, boost::hana::integral_constant<bool, true> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 3>,
      boost::hana::pair<boost::hana::basic_tuple<ecst::tag::component::impl::tag_impl<game::world_coordinate> >, boost::hana::integral_constant<bool, true> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 4>,
      boost::hana::pair<ecst::signature::system::impl::output_impl<ecst::signature::system::impl::empty_output_type>, boost::hana::integral_constant<bool, false> > > > > > >' requested here
                return data<TTag, ECST_DECAY_DECLTYPE(new_options)>{};
                       ^
/home/benjamin/github/BoomHS/external/ecst/include/ecst/signature/./system/./data.hpp:120:24: note: in instantiation of function template specialization
      'ecst::signature::system::impl::data<ecst::tag::system::impl::tag_impl<s::randompos_system>,
      ecst::mp::option_map::impl::data<boost::hana::map<boost::hana::detail::hash_table<boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 0>, 0>,
      boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 1>, 1>, boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 2>, 2>,
      boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 3>, 3>, boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 4>, 4> >,
      boost::hana::basic_tuple<boost::hana::pair<std::__1::integral_constant<unsigned long, 0>, boost::hana::pair<ecst::inner_parallelism::strategy::none::impl::parameters, boost::hana::integral_constant<bool, true> > >,
      boost::hana::pair<std::__1::integral_constant<unsigned long, 1>, boost::hana::pair<boost::hana::basic_tuple<>, boost::hana::integral_constant<bool, false> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 2>,
      boost::hana::pair<boost::hana::basic_tuple<ecst::tag::component::impl::tag_impl<game::world_coordinate> >, boost::hana::integral_constant<bool, true> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 3>,
      boost::hana::pair<boost::hana::basic_tuple<>, boost::hana::integral_constant<bool, false> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 4>,
      boost::hana::pair<ecst::signature::system::impl::output_impl<ecst::signature::system::impl::empty_output_type>, boost::hana::integral_constant<bool, false> > > > > > >::change_self<std::__1::integral_constant<unsigned long, 3>,
      boost::hana::basic_tuple<ecst::tag::component::impl::tag_impl<game::world_coordinate> > >' requested here
                return change_self(
                       ^
/home/benjamin/github/BoomHS/include/game/boomhs/ecst_systems.hpp:36:6: note: in instantiation of function template specialization 'ecst::signature::system::impl::data<ecst::tag::system::impl::tag_impl<s::randompos_system>,
      ecst::mp::option_map::impl::data<boost::hana::map<boost::hana::detail::hash_table<boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 0>, 0>,
      boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 1>, 1>, boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 2>, 2>,
      boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 3>, 3>, boost::hana::detail::bucket<boost::hana::integral_constant<unsigned long long, 4>, 4> >,
      boost::hana::basic_tuple<boost::hana::pair<std::__1::integral_constant<unsigned long, 0>, boost::hana::pair<ecst::inner_parallelism::strategy::none::impl::parameters, boost::hana::integral_constant<bool, true> > >,
      boost::hana::pair<std::__1::integral_constant<unsigned long, 1>, boost::hana::pair<boost::hana::basic_tuple<>, boost::hana::integral_constant<bool, false> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 2>,
      boost::hana::pair<boost::hana::basic_tuple<ecst::tag::component::impl::tag_impl<game::world_coordinate> >, boost::hana::integral_constant<bool, true> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 3>,
      boost::hana::pair<boost::hana::basic_tuple<>, boost::hana::integral_constant<bool, false> > >, boost::hana::pair<std::__1::integral_constant<unsigned long, 4>,
      boost::hana::pair<ecst::signature::system::impl::output_impl<ecst::signature::system::impl::empty_output_type>, boost::hana::integral_constant<bool, false> > > > > >
      >::write<ecst::tag::component::impl::tag_impl<game::world_coordinate> >' requested here
    .write(ct::world_coordinate);){}"

I boiled the error down to this minimal change:
https://github.com/bjadamson/BoomHS/commit/d36fc8b69bb59ba2a0e80316baa7af39adf1225d

I'm not sure if I'm interpreting this error message correctly, but am I allowed to read/write the same values from within a system?

set method:
https://github.com/bjadamson/BoomHS/blob/release/include/game/data_types.hpp#L68

**Comment by vittorioromeo** [comment]
Hey - everything is fine, thanks! Hope you're well too.

If you want to read/write from the same component type, just put it in `write` *(and not in `read`)*. Writing to a component implies reading from it.

I.e. this should work:

```cpp
 constexpr auto ssig_randompos_system = ss::make(st::randompos_system)
    .parallelism(PA)
    .write(ct::world_coordinate); // implies read as well!
```

**Comment by bjadamson** [comment]
Thanks, this worked as you stated it would! I'm curious, did I miss this somewhere (been a long time since I read your thesis, and I quickly glanced over the readme)?

Also, regarding the nature of the static_assert(), if it's easy for you to recall, what are you trying to prevent that both reading/writing to the same component triggered?

**Comment by vittorioromeo** [comment]
You're welcome. *(Closing the issue, but feel free to keep discussing here.)*

> Also, regarding the nature of the static_assert(), if it's easy for you to recall, what are you trying to prevent that both reading/writing to the same component triggered?

I wanted to avoid repetition/mistakes: if you want to only read a component, it should only appear in `.read`. If you want to read/write a component, it should only appear in `.write`. Having a writable but non-readable component doesn't really make sense, so I thought I would just force the component to be in `.write`.

**Comment by bjadamson** [comment]
> avoid repetition/mistakes

Makes sense! Thanks for explaining!
