### ISSUE TITLE
Checking if entity has a component

### ISSUE THREAD

**Issue by sgodwin424** [SuperV1234/ecst#24]
I am currently creating a small collision system that creates contacts similar to what is done in the particle example, but instead of outputting them from the system, the contacts are stored within a collidable component's vector. Then, from the perspective of each entity a unique system exists to perform the custom collision logic. These entities are given label components that allow for a way to differentiate entities from a high level perspective. So after an entity with, say a label component label1, has been given contacts in its collidable component, a system that reads entities with components label1 and collidable runs. It performs the custom collision logic needed for that entity type, but the problem is that there is no way to differentiate to what it is colliding with in the contact.

Obviously, depending on what you're colliding with, the logic might need to be different. But from the access given with the data proxy, it seems it's not possible to test if a given entity as a component. In my case, I simply want to check if the entity that is being collided with has a specific label component such as enemy, etc. In the case of the example code, all entities are assumed to have the same collision logic with each other because they are all particles.

I have perused the source code, and unless I missed something (which I may have), none of the proxy objects seem to give access to the necessary functions that can determine whether or not an entity has a component. So I am wondering whether or not it is possible to add a has_component function to the defer proxy class that can fulfill this role. I understand that this may have been omitted intentionally, and if so I would be interested in hearing how the above problem could be solved without it. 

I apologize if this is a bit off-topic for the project issues, and if so, I'll close it.

**Comment by vittorioromeo** [comment]
> I have perused the source code, and unless I missed something (which I may have), none of the proxy objects seem to give access to the necessary functions that can determine whether or not an entity has a component. 

You're right, this simply seems something I missed. I think it should be in the **data proxy**, as it's a simple check that does not require any critical operations. 

Feel free to send a PR *(or wait until I have some time to add and test the functionality)*.

---

The way you're dealing with collisions seems unusual, albeit interesting: just for curiosity, what are you trying to do?

**Comment by sgodwin424** [comment]
> The way you're dealing with collisions seems unusual, albeit interesting: just for curiosity, what are you trying to do?

Well, this is my first time experimenting with an entity component system, and perhaps my approach is not the best. I'm not trying to do anything special, simply attempting different ways to implement collision detection/response, though I'd be interested in what is considered the normal approach in an ECS.
