### ISSUE TITLE
Compilation error using clang 3.9 libc++ on linux

### ISSUE THREAD

**Issue by bjadamson** [SuperV1234/ecst#5]
Hey, I ran into a compiler error when I pulled in this library into my project. It's super **_easy**_ to fix, but I'd like to work out a proper solution with you.

With the code as it is, and my compiler settings as follows, I get the followoing compiler error:

> compiler=clang arch=x86 compiler.version=3.9 compiler.libcxx=libc++ build_type=Debug
> 
> End of search list.
> In file included from /home/benjamin/github/BoomHS/main.cxx:13:
> In file included from /home/benjamin/github/BoomHS/external/ecst/include/ecst.hpp:15:
> In file included from /home/benjamin/github/BoomHS/external/ecst/include/./ecst/utils.hpp:9:
> In file included from /home/benjamin/github/BoomHS/external/ecst/include/./ecst/./utils/sparse_int_set.hpp:9:
> In file included from /home/benjamin/github/BoomHS/external/ecst/extlibs/vrm_core/include/vrm/core/experimental/sparse_set.hpp:8:
> In file included from /home/benjamin/github/BoomHS/external/ecst/extlibs/vrm_core/include/vrm/core/experimental/sparse_set/base_sparse_set.hpp:8:
> In file included from /home/benjamin/github/BoomHS/external/ecst/extlibs/vrm_core/include/vrm/core/experimental/sparse_set/impl/base_sparse_set.hpp:10:
> In file included from /home/benjamin/github/BoomHS/external/ecst/extlibs/vrm_core/include/vrm/core/experimental/resizable_buffer.hpp:9:
> /home/benjamin/github/BoomHS/external/ecst/extlibs/vrm_core/include/vrm/core/experimental/resizable_buffer/multi_resizable_buffer.hpp:60:38: error: no template named 'tuple_element_t' in namespace 'std'; did you mean 'tuple_element'?
>         using nth_buffer_type = std::tuple_element_t<TN, buffer_tuple>;
>                                 ~~~~~^~~~~~~~~~~~~~~
>                                      tuple_element
> /usr/include/c++/v1/__tuple:44:62: note: 'tuple_element' declared here
> template <size_t _Ip, class _Tp> class _LIBCPP_TYPE_VIS_ONLY tuple_element;
>                                                              ^
> 1 error generated.
> make[2]: **\* [CMakeFiles/boomhs.dir/main.cxx.o] Error 1
> make[1]: **\* [CMakeFiles/boomhs.dir/all] Error 2
> make: **\* [all] Error 2

The fix (for my compiler/setup) is to change this line:
https://github.com/SuperV1234/vrm_core/blob/c0ed6218ba5f89755883ae48db92799c9c1623d2/include/vrm/core/experimental/resizable_buffer/multi_resizable_buffer.hpp#L60

from std::tuple_element_t to std::tuple_element.

Then it compiles fine. However looking at tuple element itself, it seems like the code written should be fine???
http://en.cppreference.com/w/cpp/utility/tuple/tuple_element

What are your thoughts on working around this?

**Comment by vittorioromeo** [comment]
This seems like a defect in `libc++`. What version is it? Does it happen in non-debug non-x86 versions as well?

This might need to be reported to the `libc++` tracker.

---

EDIT: `tuple_element_t` seems to be properly defined in [the latest version of `libc++` which is cloned on GitHub](https://github.com/llvm-mirror/libcxx/blob/3ec6b84545c594625bf2277ddf01493e98c02c15/include/__tuple#L449-L451).

**Comment by bjadamson** [comment]
Sorry, we could probably close this. 4.0 has been out for a long time.
